### ISSUE TITLE
yeni sürüm gelecek mi?

### ISSUE THREAD

**Issue by ghost** [okrt/usbtransfer#1]
merhaba. yeni sürümü ile ilgili çalışma varmı? flatpak sürümü olsa nasıl olur?

**Comment by okrt** [comment]
Merhaba,
İlginize teşekkürler.
Yeni sürüm planlamıyorum. Yazılımı hazırladığım zamandan bu yana çok şey değişti. Çoğu dağıtım ISO’su için Windows’ta rufus, macOS ve Linux’ta dd komutuyla benzer işlevsellik sağlanabiliyor. İlgilenmek isteyen birileri olursa py3 ve yeni pyqt uyarlamasını hazırlayabilir.

**Comment by ghost** [comment]
merhaba.bilgilendirmeniz için teşekkür.
